version: '3.3'

services:
    mysql:
        image: mysql
        ports:
            - 3306:3306
        env_file:
          - docker-compose.env/mysql.properties

    zipkin:
        image: openzipkin/zipkin
        ports:
            - 9411:9411

    eureka:
        build: ./infra/eureka
        image: marcopaga/docker-workshop-eureka
        ports:
          - 8082:8080
        environment:
          - SERVER_PORT=8080

    cars:
        build: ./services/cars
        image: marcopaga/docker-workshop-cars
        env_file:
          - docker-compose.env/cars.properties

    locations:
        build: ./services/locations
        ports:
            - 8081:8080
        env_file:
          - docker-compose.env/locations.properties

    maintenance:
        build: ./services/maintenance
        image: marcopaga/docker-workshop-maintenance
        ports:
            - 8082:8080
        env_file:
          - docker-compose.env/maintenance.properties